branches:
  only:
    - master
language: objective-c
osx_image: xcode8
cache:
  - cocoapods
env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=macOS
    - TEST_TYPE=tvOS
    - TEST_TYPE=Lint
    - TEST_TYPE=Distribution
before_install:
- |
  if [ "$TEST_TYPE" = Lint ] || [ "$TEST_TYPE" = Distribution ]; then
    brew update
  fi
install:
- |
  if [ "$TEST_TYPE" = iOS ] || [ "$TEST_TYPE" = macOS ] || [ "$TEST_TYPE" = tvOS ]; then
    gem install xcpretty -N --no-ri --no-rdoc
  elif [ "$TEST_TYPE" = Lint ]; then
    brew install swiftlint || brew upgrade swiftlint
  elif [ "$TEST_TYPE" = Distribution ]; then
    gem install cocoapods --pre --quiet --no-ri --no-rdoc
    brew install carthage || brew upgrade carthage
  fi 
script:
- |
    if [ "$TEST_TYPE" = iOS ]; then
      set -o pipefail
      xcodebuild test -project StepFlow.xcodeproj -sdk iphonesimulator -scheme StepFlow-iOS -configuration Debug -destination "platform=iOS Simulator,name=iPhone 4s" -destination "platform=iOS Simulator,name=iPhone 6 Plus" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
      xcodebuild test -project StepFlow.xcodeproj -sdk iphonesimulator -scheme StepFlow-iOS -configuration Release -destination "platform=iOS Simulator,name=iPhone 4s" -destination "platform=iOS Simulator,name=iPhone 6 Plus" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
    elif [ "$TEST_TYPE" = macOS ]; then
      set -o pipefail
      xcodebuild test -project StepFlow.xcodeproj -sdk macosx -scheme StepFlow-OSX -configuration Debug GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
      xcodebuild test -project StepFlow.xcodeproj -sdk macosx -scheme StepFlow-OSX -configuration Release GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
    elif [ "$TEST_TYPE" = tvOS ]; then
      set -o pipefail
      xcodebuild test -project StepFlow.xcodeproj -sdk appletvsimulator -scheme StepFlow-tvOS -destination "platform=tvOS Simulator,name=Apple TV 1080p" -configuration Debug GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
      xcodebuild test -project StepFlow.xcodeproj -sdk appletvsimulator -scheme StepFlow-tvOS -destination "platform=tvOS Simulator,name=Apple TV 1080p" -configuration Release GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
    elif [ "$TEST_TYPE" = Lint ]; then
      swiftlint lint
    elif [ "$TEST_TYPE" = Distribution ]; then
      pod lib lint StepFlow.podspec
      carthage build --no-skip-current
    fi
after_success:
- |
    if [ "$TEST_TYPE" = iOS ] || [ "$TEST_TYPE" = macOS ] || [ "$TEST_TYPE" = tvOS ]; then
      bash <(curl -s https://codecov.io/bash)
    fi  
